FROM nginx:stable-alpine
#Rassurer vous d'avoir le site web static-website-example dans le répertoire où se
#trouve le Dockerfile. Lien du site : https://github.com/diranetafen/static-website-example.git
COPY static-website-example/ /usr/share/nginx/html
